import { sampleVisibleTerrainHeight } from "../terrainSurface";

export const WHITE_PAVILION_CENTER = Object.freeze([40, -27]);
export const WHITE_PAVILION_BASE_Y =
  sampleVisibleTerrainHeight(
    WHITE_PAVILION_CENTER[0],
    WHITE_PAVILION_CENTER[1],
  ) + 2.8;
export const WHITE_PAVILION_SCALE = Object.freeze([2.54, 1.18, 3.1]);
export const WHITE_PAVILION_WORLD_POSITION = Object.freeze([
  WHITE_PAVILION_CENTER[0],
  WHITE_PAVILION_BASE_Y,
  WHITE_PAVILION_CENTER[1],
]);

export const WHITE_PAVILION_SCREEN_GROUP_POSITION = Object.freeze([
  0, 3.7, 4.55,
]);
const WHITE_PAVILION_SCREEN_CENTER_LOCAL = Object.freeze([0, 1.08, 0.12]);

function pavilionLocalToWorld([x, y, z]) {
  return Object.freeze([
    WHITE_PAVILION_WORLD_POSITION[0] + x * WHITE_PAVILION_SCALE[0],
    WHITE_PAVILION_WORLD_POSITION[1] + y * WHITE_PAVILION_SCALE[1],
    WHITE_PAVILION_WORLD_POSITION[2] + z * WHITE_PAVILION_SCALE[2],
  ]);
}

export const WHITE_PAVILION_SCREEN_WORLD_POSITION = pavilionLocalToWorld([
  WHITE_PAVILION_SCREEN_GROUP_POSITION[0] +
    WHITE_PAVILION_SCREEN_CENTER_LOCAL[0],
  WHITE_PAVILION_SCREEN_GROUP_POSITION[1] +
    WHITE_PAVILION_SCREEN_CENTER_LOCAL[1],
  WHITE_PAVILION_SCREEN_GROUP_POSITION[2] +
    WHITE_PAVILION_SCREEN_CENTER_LOCAL[2],
]);

export const WHITE_PAVILION_LOOK_AT_POSITION = Object.freeze([
  WHITE_PAVILION_CENTER[0],
  WHITE_PAVILION_BASE_Y + 21.5,
  WHITE_PAVILION_CENTER[1] + 0.4,
]);
export const WHITE_PAVILION_INTERIOR_CAMERA_POSITION = Object.freeze([
  WHITE_PAVILION_SCREEN_WORLD_POSITION[0],
  WHITE_PAVILION_SCREEN_WORLD_POSITION[1] + 0.14,
  WHITE_PAVILION_SCREEN_WORLD_POSITION[2] + 2.4,
]);
export const WHITE_PAVILION_INTERIOR_LOOK_AT_POSITION =
  WHITE_PAVILION_SCREEN_WORLD_POSITION;
export const WHITE_PAVILION_SWIRL_POSITION = Object.freeze([
  WHITE_PAVILION_CENTER[0],
  WHITE_PAVILION_BASE_Y + 38,
  WHITE_PAVILION_CENTER[1],
]);
